production:
  statsd:
      port: 8125
      host: "10.0.2.142"
      prefix: "production.analytics.worker"
  redis_options:
      redis_host: 'redis://production.haoefi.ng.0001.usw1.cache.amazonaws.com:6379'

staging:
  statsd:
      port: 8125
      host: "172.31.13.236"
      prefix: "staging.analytics.worker"
  redis_options:
      redis_host: 'redis://staging.haoefi.ng.0001.usw1.cache.amazonaws.com:6379'


dev-tunnel:
  statsd:
      port: 8125
      host: "172.31.13.236"
      prefix: "dev-tunnel.analytics.worker"
  redis_options:
      redis_host: 'redis://staging.haoefi.ng.0001.usw1.cache.amazonaws.com:6379'


dev:
  statsd:
      port: 8125
      host: "172.31.13.236"
      prefix: "dev.analytics.worker"
  redis_options:
      redis_host: 'redis://staging.haoefi.ng.0001.usw1.cache.amazonaws.com:6379'